apiVersion: v2
name: sd-employee-assignment
description: "BIAN Service Domain: Employee Assignment (Manage pattern, Business Support)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Business Support"
  bian/business-domain: "Human Resources"
  bian/asset-type: "Employee Assignment"
  bian/control-record: "Employee Assignment Management Plan"
